name: Test

on: [push]

jobs:
  tsc:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: 🧪 tsc
        run: npm run types

  test:
    runs-on: ubuntu-latest
    name: Lint & test with Node
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build

      - name: 🧪 Lint and test with Node ${{ env.NODE_VERSION }}
        run: |
          npm run lint
          npm run coverage

      - name: 🧪 Validate CommonJS bundle with Node ${{ env.NODE_VERSION }}
        run: npm run validate-cjs
