name: Release
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Run package release in "dry run" mode (does not publish)
        default: false
        type: boolean

jobs:
  package_release:
    name: Release from "${{ github.ref_name }}" branch
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    # GH does not allow to limit branches in the workflow_dispatch settings so this here is a safety measure
    if: ${{ inputs.dry_run || startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main') || startsWith(github.ref_name, 'rc')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: >
          npm run semantic-release
          ${{ inputs.dry_run && '--dry-run' || '' }}
